import { useState } from "react";
import { Share2, Loader2 } from "lucide-react";
import { api } from "../../lib/api";
import { site } from "../../lib/site";
import { useToast } from "../toast/ToastProvider";
import type { JobResource } from "../../types/api";

function formatRto(seconds: number | null): string {
  if (seconds == null) return "not measured";
  if (seconds < 60) return `${seconds} seconds`;
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return s > 0 ? `${m}m ${s}s` : `${m} minutes`;
}

type ShareProofButtonProps = {
  job: Pick<JobResource, "id" | "databaseId" | "status" | "rtoSeconds" | "finishedAt">;
  workflowName: string;
  variant?: "primary" | "secondary";
  className?: string;
};

export function ShareProofButton({
  job,
  workflowName,
  variant = "primary",
  className = "",
}: ShareProofButtonProps) {
  const toast = useToast();
  const [sharing, setSharing] = useState(false);
  const reportReady = ["pass", "fail", "error"].includes(job.status);

  async function shareWithManager() {
    if (!reportReady) return;
    setSharing(true);
    try {
      const runUrl = `${site.appUrl}/workflows/${job.databaseId}/runs/${job.id}`;
      const statusWord =
        job.status === "pass"
          ? "passed"
          : job.status === "fail"
            ? "failed checks"
            : "ended with an error";

      const finished = job.finishedAt
        ? new Date(job.finishedAt).toLocaleString()
        : "recently";

      const message = [
        `Restore drill update — ${workflowName}`,
        "",
        `Result: ${statusWord}`,
        `Recovery time: ${formatRto(job.rtoSeconds)}`,
        `Finished: ${finished}`,
        "",
        `View run & evidence: ${runUrl}`,
        "",
        "— Generated by Revenant Cloud (attach the PDF certificate downloaded with this action)",
      ].join("\n");

      await navigator.clipboard.writeText(message);
      await api.downloadJobReportPdf(job.id);

      toast.success(
        "Ready to share",
        "Summary copied to clipboard and PDF downloaded — paste into Slack or email."
      );
    } catch (err) {
      toast.error(
        "Share failed",
        err instanceof Error ? err.message : "Could not copy or download"
      );
    } finally {
      setSharing(false);
    }
  }

  const base =
    variant === "primary"
      ? "bg-emerald-600 text-white hover:bg-emerald-700"
      : "border border-slate-300 bg-white text-slate-800 hover:bg-slate-50";

  return (
    <button
      type="button"
      disabled={!reportReady || sharing}
      onClick={() => void shareWithManager()}
      title={
        reportReady
          ? "Copy summary for Slack/email and download PDF"
          : "Available when the run finishes"
      }
      className={`inline-flex items-center justify-center gap-2 rounded-md px-3 py-2 text-sm font-medium disabled:cursor-not-allowed disabled:opacity-50 ${base} ${className}`}
    >
      {sharing ? <Loader2 size={14} className="animate-spin" /> : <Share2 size={14} />}
      Share with manager
    </button>
  );
}
